include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    omit_local_variable_types: false
    prefer_int_literals: false
    avoid_setters_without_getters: false
    sort_constructors_first: false
    avoid_catches_without_on_clauses: false