name: copper_app
description: "A PCB Design Analysis Tool"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  # Collections and utilities functions and classes related to collections
  collection: ^1.19.1
  # Implements cryptographic functions including SHA-256
  crypto: ^3.0.6
  # Used to parse JWT tokens
  dart_jsonwebtoken: ^3.1.1
  # Allows for selecting files from the file system
  file_picker: ^9.0.0
  # The Flutter SDK
  flutter:
    sdk: flutter
  # Allows files to be dragged and dropped into the Flutter app
  flutter_dropzone: ^4.2.1
  # Used to define localizable strings
  flutter_localizations:
    sdk: flutter
  # Renders Markdown content
  flutter_markdown: ^0.7.6+2
  # Used to make REST API request
  http: ^1.3.0
  # Plugin for reading and writing simple key-value pairs
  shared_preferences: ^2.5.2
  # Provides access to browser resources
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter used internally at Very Good Ventures.
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
